apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tp-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Med-Ali02/tp-cicd.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: tp-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true