apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-gitops
  namespace: tp-gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tp-gitops
  template:
    metadata:
      labels:
        app: tp-gitops
    spec:
      containers:
        - name: tp-gitops
          image: docker.io/mohamedali2000/tp-gitops:84d70f5
          ports:
            - containerPort: 80